### ISSUE TITLE
Clean-up feature

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-test#5]
It would be highly useful if there was an option which would clean-up the output folder, removing those tests that passed and leaving just those that failed.  This would make it easier to inspect the failures to see if any of them are critical.

**Comment by rpspringuel** [comment]
Another thing that would be useful is a bit more detail in the end summary.  Instead of just saying "Something Failed", how about a count of how many tests failed, preferably classified by the reason for the failure (Differ, Failed to typeset, etc.).

**Comment by henryso** [comment]
Counting results in the end summary is difficult in the current implementation because it is based on forking processes using xargs.  Anyone have any ideas how best to do this without encountering race conditions in shell?  Or shall I rewrite the test suite in a language with better threaded programming features?

**Comment by jakubjelinek** [comment]
You could e.g. create a short Makefile on the fly and instead of the xargs run make -j $processors -k -f tmp.mk (where all: would depend on all the tests that need to be run) and let each job save status in tmpdir/$@, then once make finishes collect and merge all the status files and report overall results from it.  Or automake has some test support, you can use dejagnu, gtest, ...  Even if just using shell or shell with make, you can use the standard dejagnu
PASS testname
FAIL testname
XFAIL testname
XPASS testname
statuses, where in the final summary you report only the unexpected results (i.e. FAIL and XPASS), with some way to mark tests (perhaps under certain conditions only) as expected to fail.  If nothing is supposed to fail, you could just use PASS/FAIL.

**Comment by rpspringuel** [comment]
If each test is its own child process, couldn't the failures return a non-zero exit code based on the type of failure?  Then the parent process could check the exit codes for the child processes as they terminate and do it's counting based on that.

**Comment by henryso** [comment]
I think the Makefile is probably more viable, or maybe even just having the current method dump status files as described.  I'll look into that.  The problem with collecting error codes in the current scheme is that xargs is in between.

**Comment by henryso** [comment]
The new `-c` option will clean up if a test passes and can be made default by adding `CLEAN_PASSED=true` to `gregorio-test.rc`.  This is *not* perfect for the TeX-based tests since I didn't add any sophistication to find the included gabc files or their compiled counterparts, but it will remove the output directory.
