### ISSUE TITLE
Add a class of tests for backwards compatibility

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio-test#54]
See https://github.com/gregorio-project/gregorio/pull/702#discussion_r47181533

**Comment by rpspringuel** [comment]
My thoughts on this:

Could we create a folder `deprecated` in parallel to `tests` which has the same structure?  This folder tree would then be populated by copies of the tests in `tests` which have been effected by deprecation.  Since the folder structure is the same as `tests` this should allow us to leverage the existing infrastructure in `harness.sh` to conduct the deprecated tests (at least as far as functionality is concerned).  `gregorio-test.sh` could then have an option which flags which set of tests to run (current or deprecated).  By default, it would run the current tests.  The option could allow one to run both, but I don't think that's entirely necessary.

A harder thing to do would be to look at the log file generated in the deprecated tests and verify that the appropriate warning message appeared.  However, since the log file will, by it's nature, be very system specific, we'd have to use a tool like grep to extract just the appropriate lines before making the comparison.  Testing of this sort would obviously require some new infrastructure and I'm not sure it's entirely necessary.  I mention it, though, because a deprecation involves both backwards functionality and the raising of a warning.

**Comment by rpspringuel** [comment]
See 208a1cd for a proof of concept attempt at creating creating these tests.  Given my limited knowledge of bash, I used the longtests as my model for how to make this work.

Note: I used the name `backwards` instead of `deprecated` for the folder because both `d` and `D` were already taken in the option list but `B` was not.  I choose `B` over `b` to be consistent with longtests (where the option to include them is `L`).

The gabc-dump test of all the headers is admittedly not the best test to demonstrate backwards compatibility, but it was enough to test the functionality of what I was doing.  If others approve, then I'll start looking at populating backwards with appropriate tests.

**Comment by rpspringuel** [comment]
Hmm... Some additional testing made me realize a couple of things so I've made a couple more commits in this proof-of-concept: 8d577d6 and 6fc8688

**Comment by henryso** [comment]
I think the deprecated-feature tests should really always run.

**Comment by rpspringuel** [comment]
That's an easy enough change.  Other than that do you see any problems with my proof-of-concept?  If not I'll make those changes and submit a PR where we can start deciding what tests need to be added.
