### ISSUE TITLE
Perceptual hash is not a good enough comparison

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio-test#62]
I originally switched to perceptual hashing to try and work around slight font rendering differences between TeX Live versions (and perhaps OS as well).  However, perceptual hash is not detecting things like misplaced episemata, so I think we need to switch back to absolute error, but we need to re-evaluate how it performs between differing systems.

I'm not in a great position to do this right now, so I'm creating this issue to track this.

**Comment by rpspringuel** [comment]
[The list of possible metrics.](http://www.imagemagick.org/script/command-line-options.php#metric)

Reading through what I can find, it seems that the problem is that the difference created by a misplaced episema amounts to a few dozen pixels out of roughly 2 million.  As a result, if we use the `AE` metric we have to fave a fairly low threshold for the number of pixels that are allowed to be different.  However, font rendering differences of just four or five pixels on half-a-dozen or more letters can easily get over this threshold.

As a result, it seems that to switch back to `AE` (that was the metric we were using before) we'll need to adopt a value for `-fuzz` in the hopes that the font rendering differences will result in a change in gray shade in the transition area along the outlines of a letter, while a placement error for an episema will result in pixels making a more dramatic switch from black to white (and vis versa), thus allowing an appropriately chosen fuzz factor to differentiate between the two.

I have a final paper due on Thursday, but as soon as I finish it (which I hope will be sometime Wednesday) I'll start playing around with this to see what I can come up with.

**Comment by henryso** [comment]
In order to get through testing of my current activity, I made the change and used a fuzz of 90%, which will ignore shades of grey (for the most part), but not black to white or vice versa.  I'll push it later tonight so you can play with it if your schedule allows.

**Comment by henryso** [comment]
I created the pull request with the changes mentioned earlier.  Merge it if you need to.

**Comment by rpspringuel** [comment]
Testing on my Mac, all tests pass with TeXLive 2015 after the change.

With TeXLive 2014 we get the expected failure from `gabc-output/glyphs/clef-change` and an additional failure from`tex-output/bugs/fix-508`.  Looking at the results for this later test (attached below) I note that this is a font rendering difference, but it's a difference which is causing a 2 pixel shift in letter locations (at the density we use in the tests).  That's wider than the width of a downstroke and thus clearly will trip the white-to-black error just as much as a misplaced episema would.  As a result, I don't think there's a setting `-fuzz` which would get this test to pass while still failing on a misplaced episema.

![diff-page](https://cloud.githubusercontent.com/assets/7671682/11877963/a715577c-a4c0-11e5-9d55-fb98f1a3c981.png)

**Comment by henryso** [comment]
This one fails even with the perceptual hash.  I think it's about which version of the Linux Libertine font is being used more than anything else.  This test should probably be rewitten using the packaged Alegreya font.  I will take care of that this evening.

**Comment by henryso** [comment]
@rpspringuel Would you mind trying out the new fix-508 to see if the expectation matches on your system?

**Comment by rpspringuel** [comment]
This result passes on TeXLive 2014, but fails on TeXLive 2015 with what is basically the opposite diff from what I posted before.

**Comment by henryso** [comment]
Interesting.  So it's not the font that's causing the difference.  I'll back out that change, then.

**Comment by henryso** [comment]
Ok, I rolled that back, and since the rest work for you, I'll merge the pull request.
